### ISSUE TITLE
define Book.hpp assigned to Nika

### ISSUE THREAD

**Issue by Vorak-Tong** [Zorng/SE-G4-Group5-LibraryManagmentSystem#4]

**Comment by Zorng** [comment]
Instruction: In Book.hpp, create the 2 `class`es below.

`BookNode` can only be access by `BookList`
|BookNode | 
|---------|
|- bookID **string**|
|- bookTitle **string**  |
|- bookAuthor **string**|
|- bookPbDate **string** |
|- *prev **BookNode**|
|- *next **BookNode**|
|- bookNode **constructor** _func_|

|UserList  | 
|---------|
|- *head **BookNode**|
|- *tail **BookNode**  |
|- length **int**|
|+ BookList **constructor** _func_|
|+ getLength **int** _func_|
|+ insertFront **void** _func_|
|+ insertBack **void** _func_|
|+ removeFront **void** _func_|
|+ removeBack **void** _func_|
|+ removeByID **void** _func_|
|+ readBookDB **UserList** _func_|

More Detail:
- `insertFront` and `insertBack` have the same input argument such as `bookName`, `bookPassword`, and `bookPbDate`. `bookID` is generated automatically.
- `removeByID` have 1 argument which is`bookID`.
- `readBookDB` have 1 agrument which the file name of the DB.

**Comment by Zorng** [comment]
Successfully able to read and save. However, unable to set correct total book amount.
