### ISSUE TITLE
define Admin.hpp assigned to Vorak

### ISSUE THREAD

**Issue by Vorak-Tong** [Zorng/SE-G4-Group5-LibraryManagmentSystem#5]

**Comment by Zorng** [comment]
Instruction: In Admin.hpp, create the 2 `class`es below.

`AdminNode` can only be access by `AdminList`
|AdminNode  | 
|---------|
|- adminID **string**|
|- adminName **string**  |
|- adminPassword **string**|
|- adminBirthday **string** |
|- *prev **AdminNode**|
|- *next **AdminNode**|
|- adminNode **constructor** _func_|

|AdminList  | 
|---------|
|- *head **AdminNode**|
|- *tail **AdminNode**  |
|- length **int**|
|+ AdminList **constructor** _func_|
|+ getLength **int** _func_|
|+ insertFront **void** _func_|
|+ insertBack **void** _func_|
|+ remove_front **void** _func_|
|+ remove_back **void** _func_|
|+ removeByID **void** _func_|
|+ readUserDB **UserList** _func_|

More Detail:
- `insertFront` and `insertBack` have the same input argument such as `adminName`, `adminPassword`, and `adminBirthday`. `adminID` is generated automatically.
- `removeByID` have 1 argument which is`userID`.
- `readAdminDB` have 1 agrument which the file name of the DB.
