### ISSUE TITLE
define Transaction.hpp assigned to Nita

### ISSUE THREAD

**Issue by Vorak-Tong** [Zorng/SE-G4-Group5-LibraryManagmentSystem#6]

**Comment by Zorng** [comment]
Instruction: In Tranasction.hpp, create the 2 `class`es below.

`TranasctionNode` can only be access by `TranasctionList`
|TranasctionNode  | 
|---------|
|- tranasactionID **string**|
|- itemID **string**  |
|- actorID **string**|
|- time **string** |
|- type **string** |
|- *prev **TranasctionNode**|
|- *next **TranasctionNode**|
|- TranasctionNode **constructor** _func_|

|TranasctionList  | 
|---------|
|- *head **TranasctionNode**|
|- *tail **TranasctionNode**  |
|- length **int**|
|+ TranasctionList **constructor** _func_|
|+ getLength **int** _func_|
|+ insertFront **void** _func_|
|+ insertBack **void** _func_|
|+ remove_front **void** _func_|
|+ remove_back **void** _func_|
|+ removeByID **void** _func_|
|+ readTranasctionDB **UserList** _func_|

More Detail:
- `insertFront` and `insertBack` have the same input argument such as `itemID`, `actorID`, `type`, and `time`. `transactionID` is generated automatically.
- `removeByID` have 1 argument which is`transactionID`.
- `readTransactionDB` have 1 agrument which the file name of the DB.
